import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WalletProviderComponent from './walletProviderComponent';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HELLCAT on Solana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <WalletProviderComponent>{children}</WalletProviderComponent>
      </body>
    </html>
  );
}
